[bin]#bin目标编译为可执行文件
source = "filepath"#源文件路径，若需要多个文件编译为一个可执行文件，添加其他源文件路径语句，前提是这些源文件只能有一个主函数main
version = "1.0.0"#可执行文件版本号，默认值为0.0.1
output = "outputfilepath"#编译产物路径，若不指定，默认输出到当前目录下的vpmfile子文件夹下的build文件夹
[vxlib]#编译为vx库
version = "1.0.0"#vx库版本号，默认值为0.0.1
source = "filepath"#源文件路径，若需要多个文件编译为一个vx库，添加其他源文件路径语句
output = "outputfilepath"#编译产物路径，若不指定，默认输出到当前目录下的vpmfile子文件夹下的build文件夹
[lib]#编译为库，返回万能C调用接口
version = "1.0.0"
source = "filepath"#源文件路径，若需要多个文件编译为一个库，添加其他源文件路径语句
output = "outputfilepath"#编译产物路径，若不指定，默认输出到当前目录下的vpmfile子文件夹下的build文件夹
[module]#声明模块
info = "info.toml path"#info.toml是vack包自带的元数据，包含了模块的版本号、作者、描述等信息，存在于包安装目录下，详见pm.rs
name = "modulename"#模块在VX import语句中的调用名称
source = "filepath"#模块源文件路径，可添加多个源文件路径语句
[vxset]#vxset配置
deadcode = true#这一项允许死代码，若设置为false，编译器会报警告
cache = true#这一项开启缓存，存放于vpmfile子文件夹下的vpm文件夹的buildcache.toml文件中内部存放每次构建的情况，vpm构建器每次构建之前会读取该文件，根据文件内容判断是否需要重新构建还是增量构建或不构建使用现有，若设置为false，编译器不会开启缓存
shell = "/bin/bash"#这一项指定使用的shell，默认若不指定，会使用当前环境中的SHELL变量指定的shell
warn_to_error = true#这一项指定是否将警告转换为错误，值若为false，会将警告视为警告，值若不指定，会将警告视为警告