// ==================== OpCode ====================

#[derive(Clone, Copy, Debug, PartialEq)]
#[repr(u8)]
pub enum OpCode {
    LoadConst = 0x01,
    LoadNil = 0x02,
    LoadTrue = 0x03,
    LoadFalse = 0x04,
    LoadVar = 0x05,
    StoreVar = 0x06,
    DefineVar = 0x07,
    Call = 0x08,
    Return = 0x09,
    MakeFunction = 0x0A,
    Jump = 0x0B,
    JumpIfFalse = 0x0C,
    JumpIfTrue = 0x0D,
    Break = 0x0E,
    Continue = 0x0F,
    BinaryAdd = 0x10,
    BinarySub = 0x11,
    BinaryMul = 0x12,
    BinaryDiv = 0x13,
    BinaryMod = 0x14,
    BinaryPow = 0x15,
    BinaryEq = 0x16,
    BinaryNe = 0x17,
    BinaryLt = 0x18,
    BinaryGt = 0x19,
    BinaryLe = 0x1A,
    BinaryGe = 0x1B,
    BinaryAnd = 0x1C,
    BinaryOr = 0x1D,
    UnaryNeg = 0x1E,
    UnaryNot = 0x1F,
    MakeStruct = 0x20,
    MakeClass = 0x21,
    MakeEnum = 0x22,
    MakeUnion = 0x23,
    LoadField = 0x24,
    StoreField = 0x25,
    MakeArray = 0x26,
    MakeMap = 0x27,
    IndexGet = 0x28,
    IndexSet = 0x29,
    PropertyGet = 0x2A,
    PropertySet = 0x2B,
    AddressOf = 0x2C,
    Deref = 0x2D,
    PointerMember = 0x2E,
    Import = 0x2F,
    New = 0x30,
    Halt = 0x31,
    SysArgv = 0x32,
    System = 0x33,
    FileRead = 0x34,
    FileWrite = 0x35,
    FileExists = 0x36,
    Dup = 0x37,
    Pop = 0x38,
    // Memory Safety / Ownership
    NewZ = 0x39,
    Free = 0x3A,
    OwnershipMove = 0x3B,
    ScopeDrop = 0x3C,
    BorrowCheck = 0x3D,
    AliveCheck = 0x3E,
}

impl TryFrom<u8> for OpCode {
    type Error = String;
    fn try_from(v: u8) -> Result<Self, Self::Error> {
        match v {
            0x01 => Ok(OpCode::LoadConst),
            0x02 => Ok(OpCode::LoadNil),
            0x03 => Ok(OpCode::LoadTrue),
            0x04 => Ok(OpCode::LoadFalse),
            0x05 => Ok(OpCode::LoadVar),
            0x06 => Ok(OpCode::StoreVar),
            0x07 => Ok(OpCode::DefineVar),
            0x08 => Ok(OpCode::Call),
            0x09 => Ok(OpCode::Return),
            0x0A => Ok(OpCode::MakeFunction),
            0x0B => Ok(OpCode::Jump),
            0x0C => Ok(OpCode::JumpIfFalse),
            0x0D => Ok(OpCode::JumpIfTrue),
            0x0E => Ok(OpCode::Break),
            0x0F => Ok(OpCode::Continue),
            0x10 => Ok(OpCode::BinaryAdd),
            0x11 => Ok(OpCode::BinarySub),
            0x12 => Ok(OpCode::BinaryMul),
            0x13 => Ok(OpCode::BinaryDiv),
            0x14 => Ok(OpCode::BinaryMod),
            0x15 => Ok(OpCode::BinaryPow),
            0x16 => Ok(OpCode::BinaryEq),
            0x17 => Ok(OpCode::BinaryNe),
            0x18 => Ok(OpCode::BinaryLt),
            0x19 => Ok(OpCode::BinaryGt),
            0x1A => Ok(OpCode::BinaryLe),
            0x1B => Ok(OpCode::BinaryGe),
            0x1C => Ok(OpCode::BinaryAnd),
            0x1D => Ok(OpCode::BinaryOr),
            0x1E => Ok(OpCode::UnaryNeg),
            0x1F => Ok(OpCode::UnaryNot),
            0x20 => Ok(OpCode::MakeStruct),
            0x21 => Ok(OpCode::MakeClass),
            0x22 => Ok(OpCode::MakeEnum),
            0x23 => Ok(OpCode::MakeUnion),
            0x24 => Ok(OpCode::LoadField),
            0x25 => Ok(OpCode::StoreField),
            0x26 => Ok(OpCode::MakeArray),
            0x27 => Ok(OpCode::MakeMap),
            0x28 => Ok(OpCode::IndexGet),
            0x29 => Ok(OpCode::IndexSet),
            0x2A => Ok(OpCode::PropertyGet),
            0x2B => Ok(OpCode::PropertySet),
            0x2C => Ok(OpCode::AddressOf),
            0x2D => Ok(OpCode::Deref),
            0x2E => Ok(OpCode::PointerMember),
            0x2F => Ok(OpCode::Import),
            0x30 => Ok(OpCode::New),
            0x31 => Ok(OpCode::Halt),
            0x32 => Ok(OpCode::SysArgv),
            0x33 => Ok(OpCode::System),
            0x34 => Ok(OpCode::FileRead),
            0x35 => Ok(OpCode::FileWrite),
            0x36 => Ok(OpCode::FileExists),
            0x37 => Ok(OpCode::Dup),
            0x38 => Ok(OpCode::Pop),
            0x39 => Ok(OpCode::NewZ),
            0x3A => Ok(OpCode::Free),
            0x3B => Ok(OpCode::OwnershipMove),
            0x3C => Ok(OpCode::ScopeDrop),
            0x3D => Ok(OpCode::BorrowCheck),
            0x3E => Ok(OpCode::AliveCheck),
            _ => Err(format!("Unknown opcode: 0x{:02X}", v)),
        }
    }
}
